version: "3"
services:
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'

  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    volumes:
      - ../data:/data
      - ../letsencrypt:/etc/letsencrypt
